spring:
  application:
    name: service-auth

  redis:
    host: 192.168.1.19
    port: 6379


server:
  port: 9098
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging.level.org.springframework.security: DEBUG

